# Site settings
title: Brewhouse
email: hello@brewhouse.io
description: "Writings from brewhouse.io, makers of goodbits.io and stellar apps for our clients."

name: brewhouse
markdown: kramdown
pygments: true

paginate: 5
paginate_path: "/blog/page/:num"

exclude: ['deploy.sh', 'Gemfile', 'Gemfile.lock']
assets:
  css_compressor: sass
  js_compressor:  uglifier
