name: brewhouse
markdown: kramdown
pygments: true

paginate: 5
paginate_path: "/blog/page/:num"

exclude: ['deploy.sh', 'Gemfile', 'Gemfile.lock']
assets:
  css_compressor: sass
  js_compressor:  uglifier
