# Site settings
title: Brewhouse
email: hello@brewhouse.io
description: "Writings from brewhouse.io, the makers of goodbits.io"

name: brewhouse
markdown: kramdown
pygments: true

paginate: 8
paginate_path: "/blog/page/:num"

exclude: ['deploy.sh', 'Gemfile', 'Gemfile.lock']
assets:
  css_compressor: sass
  js_compressor:  uglifier
